### ISSUE TITLE
Not compatible with Autofac 6 changes.

### ISSUE THREAD

**Issue by Voochichichi** [erangil2/autofac.log4net#7]
When trying to use this in a solution with Autofac 6. You get the followig error

> Method not found: 'Void Autofac.Core.IComponentRegistration.add_Preparing(System.EventHandler`1<Autofac.Core.PreparingEventArgs>)'.

This is due to changes introduced 6.x where IComponentRegistration no longer exposes Preparing, Activating or Activated events.
https://autofaccn.readthedocs.io/en/latest/whats-new/upgradingfrom5to6.html

And hence lines 81 & 83 will not compile when targeting Autofac 6
https://github.com/erangil2/autofac.log4net/blob/master/src/Autofac.log4net/Log4NetModule.cs#L81

![image](https://user-images.githubusercontent.com/14302692/100931061-1d415f00-353e-11eb-84d3-3b8ae556bf48.png)

**Comment by eran-gil** [comment]
Hey @AirEssY, I've made the required adaptations in the code and pushed a new package.
Would you please try it and let me know if it works?
Thanks,

**Comment by tallalkazmi** [comment]
Hi @erangil2, after updating the package to latest version i.e. Autofac.log4net 6.0.0 and Aufofac 6.1.0, Autofac's RegisterModule throws the following exception:
`'Log4NetModule' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TModule' in the generic type or method 'ModuleRegistrationExtensions.RegisterModule<TModule>(ContainerBuilder)'`

I'm using injection is the following manner:
`var builder = new ContainerBuilder();`
`builder.RegisterModule<Log4NetModule>();`

![image](https://user-images.githubusercontent.com/31439236/106874279-d531ea80-66ee-11eb-8885-9999411c7797.png)

**Comment by eran-gil** [comment]
@tallalkazmi Hey, I fixed this in my newest version: https://www.nuget.org/packages/Autofac.log4net/6.0.1
Please let me know if this works for you.

**Comment by tallalkazmi** [comment]
@erangil2 Yes, its working now. Thanks.
